### ISSUE TITLE
Configure to use Conda Environments?

### ISSUE THREAD

**Issue by Matt-Greer** [gbingol/sciencesuit_py#3]
My apologies if this is explained in the project documentation....

I downloaded version 3.1 and extracted the files.  I attempted to run and of course, the program informed me I needed to install `wxPython`.  I'm using the Anaconda implementation of python and as such have several conda environments to segregate the different projects I'm working on to ensure I don't cause issues with certain code limitations/requirements

I created a new conda environment called `scisuit` and have installed python version 3.8.16, numpy v1.24.3,  and wxPython v 4.2.0.  Other packages are installed as well of course.

`pypkgmngr.exe` does not recognize the existence of this conda environment and therefore does not recognize the python packages that are installed.  Is there a way to configure sciencesuit to use a specific conda environment?

Thank you,

-Matt

**Comment by gbingol** [comment]
No worries!

"_...working on to ensure I don't cause issues with certain code limitations/requirements_" Once you install the packages via `pypkgmngr.exe` the packages will be installed to `SCISUITDIR/python3106` directory which by default ScienceSuit uses unless the Python Home directory has been explicitly changed.

If you would like to change the Python home directory to somewhere else then `settings.lua` file needs to be edited. Just change the `py_home` variable. There is detailed instruction in the file on how to correctly set this variable.

Coming back to your original question, it has not been tested with Conda environments.

**Comment by Matt-Greer** [comment]
Thank you for the quick reply.  I will give this a try soon and let you know if I have further issues.

**Comment by gbingol** [comment]
You are most welcome! Feel free to report if you have any issues.
